---
name: Build

on: 
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        jdk: [8, 11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build
        run: docker build -t bio-formats-build . --build-arg BUILD_IMAGE=openjdk:${{ matrix.jdk }}-slim-bullseye
